apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pltt1tlkx-go 
  janus-idp.io/tekton: pltt1tlkx-go
  backstage.io/kubernetes-id: pltt1tlkx-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pltt1tlkx-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  