apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pltt1tlkx-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pltt1tlkx-go 
  name: pltt1tlkx-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pltt1tlkx-go 
